name: CI

on: [push]

env:
  APP_NAME: playground

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      id: setup
      env:
        OUTPUT_DIR: ../output
      run: |
        # Save the path for other steps
        echo ::set-output name=output_directory::${OUTPUT_DIR}
        mkdir ${OUTPUT_DIR}
        
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo Home directory: ${HOME}
        echo Workspace dir:  ${GITHUB_WORKSPACE}
        echo Output dir from setup step: ${{ steps.setup.outputs.output_directory }}
        echo "foobar" > ${{ steps.setup.outputs.output_directory }}/test.txt
    - uses: actions/upload-artifact@v1
      id: upload_artifact
      with:
        # There's no ENV variable support for path! Only hard coded values work. I.e. the referenced value MAY NOT contain $HOME or other env values! See https://github.com/actions/upload-artifact/issues/8
        path: ${{ steps.setup.outputs.output_directory }}
        name: ${{ env.APP_NAME}}
