name: CI

on: [push]

env:
  APP_NAME: playground

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Linux Latest x64", artifact: "Linux-x64.zip",
            os: ubuntu-latest
          }
        - {
            name: "macOS Latest x64", artifact: "macOS-x64.zip",
            os: macos-latest
          }
        - {
            name: "Windows Latest x64", artifact: "Windows-x64.zip",
            os: windows-latest,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Setup
      id: setup
      # do NOT use default powershell on Windows, or env settings must be handled differently!
      # https://github.community/t5/GitHub-Actions/Env-is-null-on-windows-operating-system/m-p/37979/highlight/false#M3174
      shell: bash
      env:
        OUTPUT_DIR: "../output"
      run: |
        # Save the path for other steps
        echo "Home directory: ${HOME}"
        echo "Workspace dir:  ${GITHUB_WORKSPACE}"
        echo "Using output directory: ${OUTPUT_DIR}"
        echo "::set-output name=output_directory::${OUTPUT_DIR}"
        mkdir ${OUTPUT_DIR}
        
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo Home directory: ${HOME}
        echo Workspace dir:  ${GITHUB_WORKSPACE}
        echo Output dir from setup step: ${{ steps.setup.outputs.output_directory }}
        echo "foobar" > ${{ steps.setup.outputs.output_directory }}/test.txt
    - uses: actions/upload-artifact@v1
      id: upload_artifact
      with:
        # There's no ENV variable support for path! Only hard coded values work. I.e. the referenced value MAY NOT contain $HOME or other env values!
        # See https://github.com/actions/upload-artifact/issues/8
        path: ${{ steps.setup.outputs.output_directory }}
        name: ${{ env.APP_NAME}}-${{ matrix.config.artifact }}
